spring:
  profiles:
    active:  'daily'
  redis:
    keyPrefix: car_
    pool:
      timeout: 2000
      maxTotal: 50
      maxIdle: 5


##spring boot服务端口
server:
  port: 7001

management:
  port: 7002


multipart: 
  maxFileSize: 15Mb
    
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true 


